name: naruto_arena
dependencies:
  args: ^0.13.4
  dotenv: ^0.1.3
  string_scanner: ^1.0.0
  tuple: ^1.0.0
dev_dependencies:
  angel_common: ^1.0.0
  dart_style: ^1.0.0
  html: ^0.13.2
  recase: ^1.0.0
  test: ^0.12.0